[tool.ruff]
extend-exclude = ["notebooks/*.ipynb"]
extend-include = ["*.ipynb"]
line-length = 88

[tool.ruff.lint]
select = [
    "E",    # pycodestyle
    "F",    # Pyflakes
    "UP",   # pyupgrade
    "B",    # flake8-bugbear
    "SIM",  # flake8-simplify
    "I",    # isort
    "D",    # pydocstyle
    "C401", # flake8-comprehensions: unnecessary-generator-set
    "C402", # flake8-comprehensions: unnecessary-generator-dict
    "C403", # flake8-comprehensions: unnecessary-list-comprehension-set
    "C404", # flake8-comprehensions: unnecessary-list-comprehension-dict
    "C405", # flake8-comprehensions: unnecessary-literal-set
    "W605", # pycodestyle: invalid-escape-sequence
]

# Ignore D100,D103 Missing docstring in public module
ignore = ["D100", 'D103', 'SIM118']
[tool.ruff.lint.per-file-ignores]
# Ignore line-length errors
"src/confidentiality_patterns.py" = ["E501"]
# Also ignore `D104` in all `__init__.py` files.
"__init__.py" = ["D104"]
"tests/*.py" = ["D"]
"notebooks/*.py" = ["D103"]

[tool.ruff.lint.pydocstyle]
convention = "numpy"